files: \.py
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # should match requirements/development.txt
    hooks:
      # args are in pyproject.toml so they can be reused by IDE, command line
      - id: isort
        # config is relative to the project's .git folder
        args: ["--settings-path", "dle/pyproject.toml", "--profile", "black", "--check"]
  - repo: https://github.com/psf/black
    rev: 23.1.0  # should match requirements-dev.txt
    hooks:
      # args are in pyproject.toml so they can be reused by IDE, command line
      - id: black
        language_version: python3.10
        types: [python]
        args: [--config=dle/pyproject.toml, --check]
        files: dle\/(compare|data|dle|search|users)
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0 
    hooks:
      # args are in .flake8 file so they can be reused by IDE, command line
      - id: flake8
        additional_dependencies:
          - flake8-quotes==3.3.2
        exclude: '(migrations|tests)/.*'
        types: [python]
        args: [--config=dle/.flake8, --check]
        files: dle\/(compare|data|dle|search|users)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
